<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="suite_login" duration-ms="31" started-at="2021-07-23T08:14:07Z" finished-at="2021-07-23T08:14:07Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="31" started-at="2021-07-23T08:14:07Z" finished-at="2021-07-23T08:14:07Z">
      <class name="cn.itcast.seletest.JtTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="setUp" is-config="true" duration-ms="11" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test04()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="test04" duration-ms="1" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="SKIP" signature="test01()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="test01" duration-ms="1" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[2大于一，跳过]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 2大于一，跳过
	at cn.itcast.seletest.JtTest.test01(JtTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:968)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="SUCCESS_PERCENTAGE_FAILURE" signature="test01()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="test01" duration-ms="1" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[2大于一，跳过]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 2大于一，跳过
	at cn.itcast.seletest.JtTest.test01(JtTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:968)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="test03()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="test03" duration-ms="1" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="test02()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="test02" duration-ms="0" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:cn.itcast.seletest.JtTest@19bb089b]" name="tearDown" is-config="true" duration-ms="1" started-at="2021-07-23T16:14:07Z" finished-at="2021-07-23T16:14:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- cn.itcast.seletest.JtTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- suite_login -->
</testng-results>
